config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'welcome/index'
  
  resources :articles
  
  root 'welcome#index'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
  @articles = Article.all  
  end
  
 def new
  @article = Article.new
 end
 
  def show
    @article = Article.find(params[:id])
  end
 
def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render "new"
  end
end
 
private
  def article_params
    params.require(:article).permit(:title, :text)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">

<h1>Chat articles</h1>
 
<%= link_to 'Msg me', new_article_path , {:class=>"btn btn-primary"} %><br></br>

 
<table class="table table-striped">
  <thead></thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
  </thead>
 <tbody>
  <% @articles.each do |article| %>
    <tr>
      <th scope="row"><%= article.id %></th>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

</div>
 </div>
   </div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">


<%= simple_form_for @article, url: articles_path, local: true, 
  wrapper_mappings: 
  {
    input: :string_wrapper
  }  do |form| %>
  
<%= form.error_notification %>
    <%= form.input :title %> <br>
    <%= form.input :text %> <br>
    <%= form.button :submit, class: "btn" %>


<% end %>
<br>

<%= link_to "Back", articles_path , {:class=>"btn btn-default"} %>
 



</div>
 </div>
   </div>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>